#!/usr/bin/python3

import sys
import time
import math


def pollard_rho_factorization(n):
    if n % 2 == 0:
        return 2

    def next_value(x):
        return (x**2 + 1) % n

    x = 2
    y = 2
    gc_d = 1

    while gc_d == 1:
        x = next_value(x)
        y = next_value(next_value(y))
        gc_d = math.gcd(abs(x - y), n)

    return gc_d


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    input_filepath = sys.argv[1]

    try:
        with open(input_filepath, 'r') as f:
            lines = f.readlines()

        start_time = time.time()

        for line in lines:
            number = int(line.strip())
            factor = pollard_rho_factorization(number)

            if factor == number:
                print(f"{number} is prime.")
            else:
                print(f"{number}={factor}*{number // factor}")

            if time.time() - start_time > 5:
                print("Time limit exceeded")
                return

    except FileNotFoundError:
        print(f"File not found: {input_file}")
        return


if __name__ == '__main__':
    main()
